### ISSUE TITLE
Demutation for Vectors, Matrices and Grads indexing (non mutable, aliased references)

### ISSUE THREAD

**Issue by MxmUrw** [DiffMu/DiffPrivacyInferenceHs#183]
Vectors, matrices and grads contain references, so demutation has to track where their content goes and where it is used.

Things which deal with them:
 - Builtins that do not pass through references (always create deepcopies of their inputs)
   - `ReturnCopy`
   - `SumGrads`
   - `ZeroGrads`
 - Builtins that do pass through references
   - `Index`
   - `Sample`
 - Mutating functions

### The Problem
Using indexing, we are able to mutate matrices using assignments:
```julia
julia> m
3×3 Matrix{Any}:
  (1, 1)  2  3
 4        5  6
 7        8  9

julia> m[1,:] = [1 34 5]
1×3 Matrix{Int64}:
 1  34  5

julia> m
3×3 Matrix{Any}:
 1  34  5
 4   5  6
 7   8  9
```
The problem is that we have aliased references, as soon we use the indexing term. This is incompatible with mutation, since then mutating one of them (the vector) changes the matrix. The problem is not the statement m[1,:] = [1 34 5] itself, since that is not allowed in dmterms. The problem is that the content of the matrix may be any DMMain, which might contain types for which mutating builtins exist. Into those, the term m[1,:] might be passed.

### The Solution
We do not need matrices to be mutated. We thus create the following rule: **Vectors and Matrices are never mutated** (This is an exception to #171)

It is guaranteed by:
1. There are no builtins which mutate the types Vec/Mat
2. When accessing a part of matrix (which might be any DMMain), we give it the ImmutType `SingleRef`, which is not allowed to be passed into mutating function argument positions

And for the other vector like things we have: **DMGrads cannot be aliased**

This is guaranteed by #171.

### Example
We do not allow:
```julia
function test()
  function f!(a)
    x = a[0,0]
    convert!(x)
  end
end
```

### ToDo
 - [x] Create SingleRef type.
 - [x] Build SingleRef types when using the indexing term.
 - [x] Disallow SingleRef in mutating function calls.

**Comment by MxmUrw** [comment]
**Update**
After #185, we reimplemented the `SingleRef` functionality in terms of memory locations. The idea is the same, but instead of tracking this in the puretype, it is now tracked in the MemType.
