### ISSUE TITLE
Supremum/Infimum/LessEqual Constraint resolving needs to improve

### ISSUE THREAD

**Issue by MxmUrw** [DiffMu/DiffPrivacyInferenceHs#29]
### Aspects to consider
1. Solve cyclic subtyping and supremum/infimum constraints.The example in #26 gives a case where such constraints appear and currently cannot be solved.
  example cases are: 
     - `a <= b, b <= c, c <= a` implies `a = b = c`
     - `sup (a,b) :=c, c <= a` implies `a = c, b <= a`
2. Similarly to cyclic, we can have min/max subgraphs as in #25 which could/should be contracted
3. in `IsInfimum (τ_36,Num(τ_63[--]),Num(Int[--]))` the `τ_36` can become `Numeric` if it is free
4. there are some special cases where the infumum/supremum are `Const Int` (the minumum numeric type) or `Real` (the maximum numeric type)
5. Our subtyping/sup/inf constraints can live in different kinds. But sometimes a (e.g.) sup constraint of the form
```sup{Num a, Num b} = Num c``` should be reducible to a constraint ```sup{a,b} = c```. This relates to the "structuralness" of the involved subtyping rules
6. `IsSupremum (τ_63,Real) :=: Int` is invalid, but there is no error because we wait if there is a type variable involved.
7. If one argument of the supremum is _a_ top element (has no successors), then ```sup{a,Top} :=: x``` is equivalent to ```a <= Top``` and ```x = Top```. if we in this case simply add `x <= Top`, this becomes the second bullet point of 1.
8. we need subtyping for tuples: `a <= Tup{x,y}` implies `a = Tup{h,j}, h <= y, j <= y`
9. The constraint `constr_34 : <worst>IsSupremum (τ_62,Int) :=: τ_63`, this is similar to (7.)

### Mechanisms
| nr | problem | status | example | mechanism | notes |
| --- | --- | --- | --- | --- | --- |
| 8. | linked layers | done | `Num a <= Num b` implies `a <= b` | monadic graph walking | |
| 5. | linked layers | done | `sup{Num a, Num b} = Num c` | reconstruction of sup/inf from subtyping  | currently does not activate when non-TVars are involved, but possibly not that important |
| 1. | cycles | done | `a <= b, b <= c, c <= a` implies `a = b = c` | cycle contraction | |
| 2. | diamonds | only small dias | `a <= x, a <= y, sup{x,y} = z` | diamond contraction | only sound when no qualitatively new constraints are going to be created, thus can only be done in the end |
| 3., 6. | unknown input |  | `sup{a,Real} = Int` | Before computing the sup, we try to find paths from the args to the result | this overlaps with 9. |
| 4. | top/bottom in subtyping | done | `NonConst a <= b` | marking reflexive edges as belonging to top/bot | |
| 7. | sup with top | | `sup{a,Real} = c` | cycle contraction with virtual edges for marked tops | |
| 9. | sup with bot | | `sup{a,Int} = c` | special case in solveSupremum for marked bots | different from 7., this does not seem to be reducible to other cases |

### ToDo
 - [x] Implement cycle detection.
 - [x] Implement edge-contraction
 - [x] Solve the diamond problem (2.) using edge-contraction.  **EDIT** Implemented, testing needed.
 - [x] #38
 - [x] #41
 - [x] #42
 - [x] #43

### Possible further optimizations we currently won't do
 - #51 
 - #52

**Comment by MxmUrw** [comment]
### Possible solutions

For problem 2.:
 - Given an edge ```a <= b``` we can set ```a = b``` if `a` is a variable and there are no other constraints of the form ```X <= b```.

**Comment by MxmUrw** [comment]
As all mechanisms we are going to implement for now, are implemented: closing.
