### ISSUE TITLE
Solve subtyping constraints `a <= b` where either `a` or `b` are minimal/maximal on their graph-level

### ISSUE THREAD

**Issue by MxmUrw** [DiffMu/DiffPrivacyInferenceHs#38]
We want that constraints such as
```
a <= Int[2]
Real <= b
```
can be solved. They should be, since we know that there is nothing smaller than `Int[2]` and nothing greater than `Real` in the subtyping graph.

This does imply rewriting the MonadicGraph: Where we previously denoted edges as `reflexive-structural`, we have to split this into two properties, which combined express "structurality". Since in our new perspective, they describe the property of a subtyping-rule to be immediately commitable as soon as we know either the left, or the right hand side to match, we call them "left/right-match-forcing".

### Tasks
 - [x] Implement. Done in 471608b
 - [x] #39 
 - [x] Test the implications for subtyping.
 - [x] Test the implications for sup/inf

**Comment by ooovi** [comment]
this is at least partially a special case of #41, as for
```Real <= a```
and including virtual edges from everywhere to the top element, we get a cycle with the virtual edge
```a <= Real```
which gets resolved by regular cycle contraction. not sure about the `Int[2]` case tho, i guess we unwrap the `Int` from the `Const` and then it's also a special case of cycle contraction?

**Comment by MxmUrw** [comment]
Concerning "Test the implications for sup/inf", there are no direct ones.

That is because this mechanism of forcing some edges to be instantly committable from left or right is activated when searching for paths `a <= b`. Such a search happens in a `sup{a,b} = c` constraint only from `a` to `b`, or in the reverse direction. Furthermore, to have any effect, it must be the case that either `a` or `b` is a pure type variable. BUT: in such a case solving of the supremum is not allowed!

This is because, if we did allow it, then, e.g. in the constraint `sup{Real[--], a}`, we would find a reflexive path from `Real[--] <= a` (which actually is the only possible path) and thus set `a == Real[--]`. But that must not be necessarily the case, e.g. another valid instance would be `sup{Real[--],Int[2]} = Real[--]`.

Thus, we rather need to test that solving of sup/inf constraints where one input is unknown does not commence. (Except in well defined special cases where we actually can deduce something.)
